# Generated by Django 3.2.7 on 2021-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin_num',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
