# Generated by Django 3.2.7 on 2021-10-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0002_auto_20211012_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_structure.stock')),
            ],
        ),
    ]
