# Generated by Django 3.2.7 on 2021-10-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0004_ohcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohcl',
            name='close_p',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohcl',
            name='high_p',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohcl',
            name='low_p',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohcl',
            name='open_p',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohcl',
            name='volume',
            field=models.FloatField(),
        ),
    ]
