# Generated by Django 3.2.7 on 2021-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0005_auto_20211014_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mc_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
