# Generated by Django 3.2.7 on 2021-10-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0006_stock_mc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_structure.stock')),
            ],
        ),
    ]
