# Generated by Django 3.2.7 on 2021-10-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0008_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHCLI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_p', models.FloatField()),
                ('high_p', models.FloatField()),
                ('low_p', models.FloatField()),
                ('close_p', models.FloatField()),
                ('volume', models.FloatField()),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_structure.indices')),
            ],
        ),
    ]
