# Generated by Django 3.2.7 on 2021-10-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0009_ohcli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohcli',
            name='volume',
        ),
    ]
